name: Create Sentry release

on:
    push:
        branches:
            - master

jobs:
    sentry-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Create Sentry release
              uses: getsentry/action-release@v1
              env:
                SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
              with:
                environment: production
                version: ${{ node -p "require('./package.json').version" }}
